<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use App\Models\Department;

class DepartmentSeeder extends Seeder {
    public function run(): void {
        $data = [
            [
                'name' => 'Office of the Vice President for Academic Affairs',
                'short_name' => 'OVPAA',
                'email' => 'vpaa@cmu.edu.ph',
                'phone_number' => 9176761411,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'College of Agriculture',
                'short_name' => 'CA',
                'email' => 'agriculture@cmu.edu.ph',
                'phone_number' => 9751061074,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'College of Arts & Sciences',
                'short_name' => 'CAS',
                'email' => 'registrar.cas@cmu.edu.ph',
                'phone_number' => null,
                'image_url' => '/images/cmu.png',

            ],
            [
                'name' => 'College of Business and Management',
                'short_name' => 'CBM',
                'email' => 'cbm@cmu.edu.ph',
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'College of Information, Sciences and Computing',
                'short_name' => 'CISC',
                'email' => 'cisc@cmu.edu.ph',
                'phone_number' => 9262132004,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'College of Education',
                'short_name' => 'COEd',
                'email' => 'education@cmu.edu.ph',
                'phone_number' => 9203294942,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'College of Engineering',
                'short_name' => 'COE',
                'email' => 'coe@cmu.edu.ph',
                'phone_number' => 9353958071,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'College of Forestry and Environmental Science',
                'short_name' => 'CFES',
                'email' => 'cfes@cmu.edu.ph',
                'phone_number' => 9353958071,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'College of Human Ecology',
                'short_name' => 'CHE',
                'email' => 'che@cmu.edu.ph',
                'phone_number' => 9273155884,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'College of Nursing',
                'short_name' => 'CON',
                'email' => 'con@cmu.edu.ph',
                'phone_number' => 9121411103,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'College of Veterinary Medicine',
                'short_name' => 'CVM',
                'email' => 'cvm@cmu.edu.ph',
                'phone_number' => 9533619611,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of Instruction',
                'short_name' => 'DI',
                'email' => 'dioffice@cmu.edu.ph',
                'phone_number' => 9177170572,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of Quality Assurance',
                'short_name' => 'OQA',
                'email' => 'qualityassuranceoffice@cmu.edu.ph',
                'phone_number' => 9121411220,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of the National Service Training Program',
                'short_name' => 'NSTP',
                'email' => 'nstp@cmu.edu.ph',
                'phone_number' => 9178083312,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of Admissions, Scholarships and Placement',
                'short_name' => 'OASP',
                'email' => 'oasp@cmu.edu.ph',
                'phone_number' => 9177103100,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of the University Registrar',
                'short_name' => 'OUR',
                'email' => 'registrar@cmu.edu.ph',
                'phone_number' => 9177084651,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of Student Affairs and Services',
                'short_name' => 'OSA',
                'email' => 'osa@cmu.edu.ph',
                'phone_number' => 9121411071,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of the Library Services',
                'short_name' => 'OLS',
                'email' => 'library@cmu.edu.ph',
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of the International Relations',
                'short_name' => 'OIR',
                'email' => 'intlrelationsoffice@cmu.edu.ph',
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],

            [
                'name' => 'Office of the Vice President for Research, Development and Extension',
                'short_name' => 'OVPRDE',
                'email' => 'vprde@cmu.edu.ph',
                'phone_number' => 9177181727,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of Research',
                'short_name' => 'Research',
                'email' => 'researchoffice@cmu.edu.ph',
                'phone_number' => 9171081439,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of Extension',
                'short_name' => 'Extension',
                'email' => 'extensiondo@cmu.edu.ph',
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Capability Building Unit',
                'short_name' => 'CBU',
                'email' => 'cbuextension@cmu.edu.ph',
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Information & Communication Unit',
                'short_name' => 'ICU',
                'email' => 'dxmu-fm@cmu.edu.ph',
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Monitoring Evaluation and Documentation Unit',
                'short_name' => 'MEDU',
                'email' => null,
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Techno Demo Services Unit',
                'short_name' => 'TDSU',
                'email' => null,
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Center for Biodversity Research and Extension in Mindanao',
                'short_name' => 'CEBREM',
                'email' => 'cebrem@cmu.edu.ph',
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Center for Natural Products Research Development and Extension',
                'short_name' => 'CNPRDE',
                'email' => 'nprdc@cmu.edu.ph',
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Center for Agricultural Experiment',
                'short_name' => 'CAE',
                'email' => 'aecenter@cmu.edu.ph',
                'phone_number' => 9751061074,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Center for Geomatics Research and Development in Mindanao',
                'short_name' => 'CGRDM',
                'email' => null,
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Center for Food Research, Innovation and Extension',
                'short_name' => 'CFRD',
                'email' => 'frdc@cmu.edu.ph',
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'University Press',
                'short_name' => 'Press',
                'email' => 'press@cmu.edu.ph',
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of Intellectual Property and Technology Business Management',
                'short_name' => 'OIPTBM',
                'email' => 'iptbm@cmu.edu.ph',
                'phone_number' => 9753618049,
                'image_url' => '/images/cmu.png',
            ],

            [
                'name' => 'Office of the Vice President for Resource Generation and Management',
                'short_name' => 'OVPRGMO',
                'email' => 'vprgmo@cmu.edu.ph',
                'phone_number' => 9364291869,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of Resource Generation and Management',
                'short_name' => 'RGMO',
                'email' => 'rgmo@cmu.edu.ph',
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of Crops Enterprise',
                'short_name' => 'CEO',
                'email' => 'rgmo.ceo@cmu.edu.ph',
                'phone_number' => 9364291869,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'University Homestay',
                'short_name' => 'UH',
                'email' => 'hsfeo@cmu.edu.ph',
                'phone_number' => 9364291869,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of the Tourism',
                'short_name' => 'Tourism',
                'email' => 'cmutourism.office@cmu.edu.ph',
                'phone_number' => 9177070381,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of Livestock Enterprise',
                'short_name' => 'Livestock',
                'email' => 'rgmo.livestock@cmu.edu.ph',
                'phone_number' => 9364291869,
                'image_url' => '/images/cmu.png',
            ],

            [
                'name' => 'Office of the Vice President for Administration',
                'short_name' => 'OVPA',
                'email' => 'vpa@cmu.edu.ph',
                'phone_number' => 9667046661,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of the Alumni Relations & Linkages',
                'short_name' => 'OARL',
                'email' => 'alumnirelation@cmu.edu.ph',
                'phone_number' => 9054411023,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of the Public Relations & Information',
                'short_name' => 'OPRI',
                'email' => 'prio@cmu.edu.ph',
                'phone_number' => 9173016681,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Center for Gender and Development',
                'short_name' => 'GAD',
                'email' => 'ucgad@cmu.edu.ph',
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of the Legal Counsel',
                'short_name' => 'Legal',
                'email' => 'cmulegal@cmu.edu.ph',
                'phone_number' => 9177070321,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of the Project Implementation',
                'short_name' => 'OPIU',
                'email' => 'piu@cmu.edu.ph',
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of the University Planning and Development',
                'short_name' => 'OUPD',
                'email' => 'updo@cmu.edu.ph',
                'phone_number' => 9178802460,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of the Bids and Award Committee',
                'short_name' => 'BAC',
                'email' => 'bac@cmu.edu.ph',
                'phone_number' => 9177182368,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of the Journal of Science',
                'short_name' => 'OJS',
                'email' => 'journalofscience@cmu.edu.ph',
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of the Internal Audit Services',
                'short_name' => 'OIAS',
                'email' => 'ias.iso@cmu.edu.ph',
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Office of the Financial Management Services',
                'short_name' => 'OFMS',
                'email' => 'financialmanagement@cmu.edu.ph',
                'phone_number' => 9177023898,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Accounting Unit',
                'short_name' => 'Accounting',
                'email' => 'accounting@cmu.edu.ph',
                'phone_number' => 9177070349,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => 'Budget Unit',
                'short_name' => 'Budget',
                'email' => 'budget.office@cmu.edu.ph ',
                'phone_number' => 9177070349,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => "Cashier\'s Unit",
                'short_name' => 'Cashier',
                'email' => 'cashier@cmu.edu.ph',
                'phone_number' => 9777446369,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => "Office of General Services",
                'short_name' => 'OGS',
                'email' => 'gso@cmu.edu.ph',
                'phone_number' => 9171064781,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => "Office of the Inspectorate Team for Supplies & Materials",
                'short_name' => 'ITSM',
                'email' => 'itsm@cmu.edu.ph',
                'phone_number' => 9777784694,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => "Office of Human Resource Management",
                'short_name' => 'OHRM',
                'email' => 'hrmo@cmu.edu.ph',
                'phone_number' => 9178883281,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => "Office of Administrative Services",
                'short_name' => 'Admin',
                'email' => 'aso@cmu.edu.ph',
                'phone_number' => 9177773870,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => "Office of Health Services",
                'short_name' => 'Hospital',
                'email' => 'hospital@cmu.edu.ph',
                'phone_number' => 9171279528,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => "Office of Disaster Risk Reduction and Management",
                'short_name' => 'ODRM',
                'email' => 'drrmo@cmu.edu.ph',
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => "Office of Digital Transformation",
                'short_name' => 'DTO',
                'email' => 'dto@cmu.edu.ph',
                'phone_number' => 9121411406,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => "Office of Supply and Property Management",
                'short_name' => 'SPMU',
                'email' => 'spmu@cmu.edu.ph',
                'phone_number' => 9178804029,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => "Office of Branding Office",
                'short_name' => 'OBM',
                'email' => 'obm@cmu.edu.ph',
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => "Tuklas Lunas Development Center",
                'short_name' => 'TLDC',
                'email' => null,
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => "National Service Reserve Corps",
                'short_name' => 'NSRC',
                'email' => null,
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => "Office of Security Services",
                'short_name' => 'OSS',
                'email' => null,
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => "University Housing and Relocation Committee",
                'short_name' => 'UHRC',
                'email' => null,
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => "Office of the President",
                'short_name' => 'OP',
                'email' => null,
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => "Disaster Risk Reduction Management Office",
                'short_name' => 'DRRMO',
                'email' => null,
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => "Records Management Unit",
                'short_name' => 'RMU',
                'email' => null,
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
            [
                'name' => "Office of Environmental and Safety Management",
                'short_name' => 'OESM',
                'email' => null,
                'phone_number' => null,
                'image_url' => '/images/cmu.png',
            ],
        ];

        foreach ($data as $row) {
            Department::create($row);
        }
    }
}
