/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key",
            "required": true
        },
        {
            "name": "tags",
            "required": false
        }
    ],
    "debugbar.queries.explain": [],
    "sanctum.csrf-cookie": [],
    "laratrust.permissions.index": [],
    "laratrust.permissions.create": [],
    "laratrust.permissions.store": [],
    "laratrust.permissions.edit": [
        {
            "name": "permission",
            "required": true
        }
    ],
    "laratrust.permissions.update": [
        {
            "name": "permission",
            "required": true
        }
    ],
    "laratrust.roles.index": [],
    "laratrust.roles.create": [],
    "laratrust.roles.store": [],
    "laratrust.roles.show": [
        {
            "name": "role",
            "required": true
        }
    ],
    "laratrust.roles.edit": [
        {
            "name": "role",
            "required": true
        }
    ],
    "laratrust.roles.update": [
        {
            "name": "role",
            "required": true
        }
    ],
    "laratrust.roles.destroy": [
        {
            "name": "role",
            "required": true
        }
    ],
    "laratrust.roles-assignment.index": [],
    "laratrust.roles-assignment.edit": [
        {
            "name": "roles_assignment",
            "required": true
        }
    ],
    "laratrust.roles-assignment.update": [
        {
            "name": "roles_assignment",
            "required": true
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "arta-id-verify.store": [],
    "setup.store": [],
    "setup.show": [
        {
            "name": "setup",
            "required": true
        }
    ],
    "index": [],
    "guest-qr-codes.index": [],
    "guest-qr-codes.store": [],
    "guest-qr-codes.destroy": [
        {
            "name": "guest_qr_code",
            "required": true
        }
    ],
    "arta-id.index": [],
    "arta-id.store": [],
    "arta-id.show": [
        {
            "name": "arta_id",
            "required": true
        }
    ],
    "arta-id.edit": [
        {
            "name": "arta_id",
            "required": true
        }
    ],
    "arta-id.update": [
        {
            "name": "arta_id",
            "required": true
        }
    ],
    "arta-id.destroy": [
        {
            "name": "arta_id",
            "required": true
        }
    ],
    "feedbacks.index": [],
    "link.show": [
        {
            "name": "name",
            "required": true
        }
    ],
    "qr.redirect": [
        {
            "name": "id",
            "required": true
        }
    ],
    "login": [],
    "login.submit": [],
    "logout": [],
    "dashboard.index": [],
    "dashboard.guest-qr.index": [],
    "dashboard.guest-qr.create": [],
    "dashboard.guest-qr.store": [],
    "dashboard.guest-qr.edit": [
        {
            "name": "guest_qr",
            "required": true
        }
    ],
    "dashboard.guest-qr.update": [
        {
            "name": "guest_qr",
            "required": true
        }
    ],
    "dashboard.guest-qr.destroy": [
        {
            "name": "guest_qr",
            "required": true
        }
    ],
    "dashboard.request-statuses.index": [],
    "dashboard.request-statuses.update": [
        {
            "name": "request_status",
            "required": true
        }
    ],
    "dashboard.arta_id.prints": [],
    "dashboard.arta-id.index": [],
    "dashboard.arta-id.show": [
        {
            "name": "arta_id",
            "required": true
        }
    ],
    "dashboard.arta-id.edit": [
        {
            "name": "arta_id",
            "required": true
        }
    ],
    "dashboard.arta-id.update": [
        {
            "name": "arta_id",
            "required": true
        }
    ],
    "dashboard.arta-id.destroy": [
        {
            "name": "arta_id",
            "required": true
        }
    ],
    "dashboard.users.prints": [],
    "dashboard.users.index": [],
    "dashboard.users.create": [],
    "dashboard.users.store": [],
    "dashboard.users.edit": [
        {
            "name": "user",
            "required": true
        }
    ],
    "dashboard.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.galleries.index": [],
    "dashboard.departments.index": [],
    "dashboard.departments.create": [],
    "dashboard.departments.store": [],
    "dashboard.departments.show": [
        {
            "name": "department",
            "required": true
        }
    ],
    "dashboard.departments.edit": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.departments.update": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.departments.destroy": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.data-configurations.index": [],
    "dashboard.data-configurations.store": [],
    "dashboard.data-configurations.show": [
        {
            "name": "data_configuration",
            "required": true
        }
    ],
    "dashboard.data-configurations.update": [
        {
            "name": "data_configuration",
            "required": true
        }
    ],
    "dashboard.data-configurations.destroy": [
        {
            "name": "data_configuration",
            "required": true
        }
    ],
    "dashboard.notifications.index": [],
    "dashboard.notifications.store": [],
    "dashboard.notifications.update": [
        {
            "name": "notification",
            "required": true
        }
    ],
    "dashboard.roles-permissions.index": [],
    "dashboard.roles-permissions.create": [],
    "dashboard.roles-permissions.store": [],
    "dashboard.roles-permissions.show": [
        {
            "name": "roles_permission",
            "required": true
        }
    ],
    "dashboard.roles-permissions.edit": [
        {
            "name": "roles_permission",
            "required": true
        }
    ],
    "dashboard.roles-permissions.update": [
        {
            "name": "roles_permission",
            "required": true
        }
    ],
    "dashboard.roles-permissions.destroy": [
        {
            "name": "roles_permission",
            "required": true
        }
    ],
    "dashboard.account-settings.store": [],
    "dashboard.account-settings.show": [
        {
            "name": "account_setting",
            "required": true
        }
    ],
    "dashboard.gemini.index": [],
    "dashboard.gemini.store": [],
    "dashboard.gemini.destroy": [
        {
            "name": "gemini",
            "required": true
        }
    ]
}
}
export {};
